---
- name: installing redis-server
  apt: name=redis-server state=present

- name: copying Redis config
  copy: src="redis.conf" dest=/etc/redis mode=755

- name: starting/restarting redis-server
  service: name=redis-server state=restarted
  async: 45
  poll: 0
