---
- name: installing redis-server
  yum: pkg=redis update_cache=yes

- name: copying Redus config
  copy: src="redis.conf" dest=/etc mode=755

- name: starting/restarting redis-server
  service: name=redis state=restarted
  async: 45
  poll: 0
