---

- name: Copy script to test Hdfs read/write operations
  copy: src="{{item}}" dest=/tmp mode=755
  with_items:
    - 1_hdfs.sh
    - common.sh


- name: Test hdfs read/write operations
  become: yes
  become_user: hdfs
  register: out
  command: /tmp/1_hdfs.sh

- debug: var=out.stdout_lines