---

- name: Copy script to test Hdfs read/write operations
  copy: src="{{item}}" dest=/tmp mode=755
  with_items:
    - 1_hdfs.sh


- name: Test hdfs read/write operations
  become: yes
  become_user: hdfs
  command: /tmp/1_hdfs.sh