- hosts: localhost
  connection: local
  roles:
     - role: cm-api-libs
     - role: get-hue-db-password
#     - role: install-kafka
#     - role: enable-hdfs-ha

#     Please edit which services will be configured in role configuration
#     - role: service-config-changes
