- hosts: all
  gather_facts: false
  tasks:
    - lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - user:
        name: cdh
        uid: 10001
        password: "$6$g0Faz/hHO$iVOy/keiRcCRmMmTN3G0FOCdKdWHDZqBzbDKX4idXSeibGnaSyiTDIiy.RCN2ay.ZIxqp40DKURDO/Pxbcqak1"
        groups: wheel 
