---

- name: Add maven repo
  get_url: 
    url: http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
    dest: /etc/yum.repos.d/epel-apache-maven.repo 

- name: Install maven
  yum: pkg=apache-maven update_cache=yes

