---
- name: Copy scripts
  copy: src="{{item}}" dest=/home/ec2-user mode=755
  with_items:
    - install_confluent.sh
    - start_confluent.sh
- name: Install Confluent from script
  shell: ./install_confluent.sh
  args:
    chdir: /home/ec2-user

#- name: Start Confluent components from script
#  shell: ./start_confluent.sh
#  args:
#    chdir: /home/ec2-user

- include: kafka.yml
  tags: [kafka]

- include: zookeeper.yml
  tags: [zookeeper]
