---
#
# Installs packages required for Ansible on RedHat/CentOS hosts.
#

- name: Install minimal requirements for Ansible (on RedHat/Centos)
  script: yum_install_missing_package.sh {{item}}
  register: res
  changed_when: "res.stdout.startswith('Install')"
  with_items:
     - python
     - python-pycurl
  when: ansible_os_family == "Redhat"

- name: Install minimal requirements for Ansible (on Debian/Ubuntu)
  script: apt_install_missing_package.sh {{item}}
  register: res
  changed_when: "res.stdout.startswith('Install')"
  with_items:
     - python
     - python-pycurl
  when: ansible_os_family == "Debian"
