---

- name: Install minimal requirements for Ansible
  script: install_missing_package.sh {{item}}
  register: res
  changed_when: "res.stdout.startswith('Install')"
  with_items:
     - python
     - python-pycurl

#- name: Install minimal requirements for Ansible (on Debian/Ubuntu)
#  script: apt_install_missing_package.sh {{item}}
#  register: res
#  changed_when: "res.stdout.startswith('Install')"
#  with_items:
#     - python
#     - python-pycurl
#  when: ansible_os_family == "Debian"
