---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: generating hashed credentials file
  command: /usr/sbin/postmap /etc/postfix/sasl_passwd
  become: true
  become_user: root

- name: starting/restarting postfix
  service: name=postfix state=restarted
  async: 45
  poll: 0
