---
- name: installing postfix
  yum: pkg=postfix update_cache=yes

- name: installing postfix
  yum: pkg=cyrus-sasl-plain state=present

- name: installing postfix
  yum: pkg=cyrus-sasl-md5 state=present

- name: copying api credentials
  copy: src="sasl_passwd" dest=/etc/postfix mode=600

- name: copying postfix config
  copy: src="main.cf" dest=/etc/postfix mode=600
