aws_keypair: "zarz"
aws_image: "ami-2cf8901c"
aws_region: "us-west-2"
aws_group: "default"
aws_instance_type: "t1.micro"
aws_quantity: 1
aws_acct_vpc_id: "vpc-09f4c86c"
aws_vpc_subnet: "vpc-09f4c86c"
app_name: test
server_env: qa


# Don't put here keys explicitly! We would figure out how to store those values in encrypted files later on.
aws_ec2_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID }}"
aws_ec2_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY }}"
