# tasks file for cdh
---
- name: Copy script for CM
  copy: src="{{item}}" dest=/tmp/ owner=root group=root mode=0777
  with_items:
    - configure-hue-db.sh
    - schema.sql
    - cm-setup.sh
    - cdh-setup.py

- name: Configure HUE db
  command: /tmp/configure-hue-db.sh
  become: yes
  become_user: root

- name: run CM script
  command: /tmp/cm-setup.sh

- name: execute CDH setup
  command: /tmp/cdh-setup.py --cmhost cdh-master-01.c.getindata-training.internal --nodes cdh-master-01.c.getindata-training.internal  cdh-slave-01.c.getindata-training.internal cdh-slave-02.c.getindata-training.internal cdh-slave-03.c.getindata-training.internal cdh-slave-04.c.getindata-training.internal cdh-edge-01.c.getindata-training.internal
