# tasks file for cdh
---
- name: upload schema.sql
  copy: src=schema.sql dest=/tmp/schema.sql owner=root group=root mode=0777

- name: upload CM script
  copy: src=cm-setup.sh dest=/tmp/cm-setup.sh owner=root group=root mode=0777

- name: run CM script
  command: /tmp/cm-setup.sh

- name: upload CDH setup script
  copy: src=cdh-setup.py dest=/tmp/cdh-setup.py owner=root group=root mode=0777

- name: execute CDH setup
  command: /tmp/cdh-setup.py --cmhost --nodes
