---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: downloading storm 0.9.2
  command: wget http://www-eu.apache.org/dist/storm/apache-storm-0.9.2-incubating/apache-storm-0.9.2-incubating.zip -O /tmp/apache-storm-0.9.2-incubating.zip

- name: unpacking storm to /opt/storm
  command: unzip -u /tmp/apache-storm-0.9.2-incubating.zip -d /opt

#- name: copy config
#  copy: src="storm.yaml" dest=/opt/apache-storm-0.10.0/conf mode=755

- name: copy supervisor includes for Storm
  copy: src="{{item}}" dest=/etc/supervisor/conf.d/ mode=755
  with_items:
    - storm-supervisor.conf

- name: starting/restarting supervisord
  service: name=supervisord state=restarted
  async: 45
  poll: 0
