---
- name: Install dev packages
  yum: pkg={{item}}
  with_items:
    - git
    - wget
    - curl
    - vim
    - jq

- name: Add maven repo
  get_url: 
    url: http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
    dest: /etc/yum.repos.d/epel-apache-maven.repo 

- name: Install maven
  yum: pkg=apache-maven update_cache=yes

- name: install numpy
  yum: name=numpy state=latest

- name: install krb5-workstation
  yum: name=krb5-workstation state=latest

- name: install krb5-libs
  yum: name=krb5-libs state=latest
