---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: adding group kibana
  group: name=kibana state=present

- name: adding user kibana
  user: name=kibana comment="kibana" group=kibana

- name: downloading kibana 4.5.0
  command: wget https://download.elastic.co/kibana/kibana/kibana-4.5.0-linux-x64.tar.gz -O /tmp/kibana-4.5.0-linux-x64.tar.gz

- name: unpacking kibana to /opt/kibana-4.5.0-linux-x64
  command: tar -zxf /tmp/kibana-4.5.0-linux-x64.tar.gz -C /opt

- name: changing ownership of kibana homedir to kibana user
  file: path=/opt/kibana-4.5.0-linux-x64 state=directory owner=kibana group=kibana mode=0755 recurse=yes

- name: copying supervisor includes for Kibana
  copy: src="{{item}}" dest=/etc/supervisor/conf.d/ mode=755
  with_items:
    - kibana.conf

- name: starting/restarting supervisord
  service: name=supervisord state=restarted
  async: 45
  poll: 0

