---
- name: copy config
  copy: src="storm.yaml" dest=/opt/apache-storm-0.9.2-incubating/conf mode=755

- name: Restarting Storm Nimbus
  command: supervisorctl restart storm-nimbus
  ignore_errors: true

- name: Restarting Storm Supervisor
  command: supervisorctl restart storm-supervisor
  ignore_errors: true

- name: Restarting Storm UI
  command: supervisorctl restart storm-ui
  ignore_errors: true

- name: starting/restarting supervisord
  service: name=supervisord state=restarted
  async: 45
  poll: 0 
