---
- name: Copy script to install hue
  copy: src="{{item}}" dest=/tmp/ mode=755
  with_items:
    - configure-hue-db.sh

- name: install mysql client
  yum: name=mysql state=latest

- name: install the mysql rpm from a remote repo
  yum: name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm state=present

- name: install mysql server
  yum: name=mysql-server state=latest

- name: install the MySQL client developer package
  yum: name=mysql-devel state=latest

- name: install the MySQL connector
  yum: name=mysql-connector-java state=latest

- name: configure /etc/my.cnf to use default-storage-engine=InnoDB
  lineinfile: dest=/etc/my.cnf regexp=^default-storage-engine= line=default-storage-engine=InnoDB

- name: configure /etc/my.cnf to use sql_mode=STRICT_ALL_TABLES
  lineinfile: dest=/etc/my.cnf regexp=^sql_mode= line=sql_mode=STRICT_ALL_TABLES

- name: start mysql server
  service: name=mysqld state=started

- name: Configure HUE db
  command: /tmp/configure-hue-db.sh
  become: yes
  become_user: root

- name: copy hue.ini config file 
  copy: src="{{item}}" dest=/etc/hue/conf owner=root group=root mode=755
  with_items:
    - hue.ini
