- name: Disable and stop NTP daemon
  service:
    name: ntpd
    state: stopped
    enabled: no

- name: Enable and start Chrony daemon
  service:
    name: chronyd
    state: started
    enabled: yes
