---

- name: Copy scripts to test Kafka
  copy: src="{{item}}" dest=/tmp mode=777 #needs to be 777 for user hdfs to execute
  with_items:
    - 4_kafka.sh
    - common.sh
    - kafka_test.py

- name: Test Kafka operations
  become: yes
  become_user: hdfs
  register: out
  command: /tmp/4_kafka.sh

- debug: var=out.stdout_lines