---

- name: Copy scripts to test Kafka
  copy: src="{{item}}" dest=/tmp mode=777 #the file permission needs to be 777 because hdfs user needs to be able to sed changes into kafka_test.py
  with_items:
    - 4_kafka.sh
    - common.sh
    - kafka_test.py

- name: Test Kafka operations
  become: yes
  become_user: hdfs
  register: out
  command: /tmp/4_kafka.sh

- debug: var=out.stdout_lines

- name: install python-kafka libs
  pip: name=kafka-python