---

- name: remove local training directory and files
  file: path={{ item }} state=absent
  with_items:
    - "{{ training_dir }}"
    - 'streamrock.zip'


- name: create local training directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ training_dir }}"
    - "{{ training_jar_dir }}"
    - "{{ training_data_dir }}"

- name: download avro tools
  get_url: url=http://central.maven.org/maven2/org/apache/avro/avro-tools/1.7.7/avro-tools-1.7.7.jar dest={{ training_jar_dir }} mode=0755


- name: download streamrock zip
  command: wget https://www.dropbox.com/s/u5tlk8kts005qim/streamrock.zip

- name: download and unarchive streamrock.zip
  unarchive: src=streamrock.zip dest={{ training_data_dir }} copy=no


- name: remove hdfs directory
  command: hdfs dfs -rm -r -f {{ training_data_dir }}
  become: yes
  become_user: hdfs


- name: create hdfs directories
  command: hdfs dfs -mkdir -p {{ item }}
  become: yes
  become_user: hdfs
  with_items:
    - "{{ training_data_dir }}/user"
    - "{{ training_data_dir }}/streamsimple"
    - "{{ training_data_dir }}/stream"
    - "{{ training_data_dir }}/track"
    - "{{ training_data_dir }}/wordhappiness"
    - "{{ training_data_dir }}/playedWithMetadata"
    - "{{ training_data_dir }}/flight"
    - "{{ training_data_dir }}/airport"
    - "{{ training_data_dir }}/lyrics"
    - "/incoming/logs/upload"


- name: chmod incoming directories
  command: hdfs dfs -chmod -R 777 /incoming
  become: yes
  become_user: hdfs


- name: upload data to HDFS
  command: hdfs dfs -put {{ training_data_dir }}/{{ item.file }} {{ training_data_dir }}/{{ item.dir }}
  become: yes
  become_user: hdfs
  with_items:
    - { file: 'users.tsv', dir: 'user' }
    - { file: 'played.tsv', dir: 'streamsimple' }
    - { file: 'stream.tsv', dir: 'stream' }
    - { file: 'song.tsv', dir: 'track' }
    - { file: 'wordhappiness.tsv', dir: 'wordhappiness' }
    - { file: 'playedWithMetadata.tsv', dir: 'playedWithMetadata' } 
    - { file: 'lyrics.avro', dir: 'lyrics' }
    - { file: 'user.parquet', dir: '.' }


- name: Copy scripts
  copy: src="{{ item }}" dest=/home/ec2-user mode=755
  with_items:
    - create-core-hive-tables.sh


- name: recreate Hive tables
  command: /home/ec2-user/create-core-hive-tables.sh {{ training_data_dir }}
