# tasks file for cdh

- name: creating home directory for users
  command: hdfs dfs -mkdir -p /user/admin
  become: yes
  become_user: hdfs

- name: chowning home directory for users
  command: hdfs dfs -chown admin /user/admin
  become: yes
  become_user: hdfs

- name: submitting teragen job
  command: hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen 10000 teragen1MB
  become: yes
  become_user: admin

- name: submitting pi estimator
  command: hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar pi 1 1000
  become: yes
  become_user: admin
