# tasks file for cdh

- name: creating home directory for users
  command: hdfs dfs -mkdir -p /user/ec2-user
  become: yes
  become_user: hdfs

- name: chowning home directory for users
  command: hdfs dfs -chown ec2-user /user/ec2-user
  become: yes
  become_user: hdfs

- name: submitting teragen job
  command: hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen 5000000 teragen500MB
  become: yes
  become_user: ec2-user

- name: submitting pi estimator
  command: hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar pi 10 1000000
  become: yes
  become_user: ec2-user
