---
# tasks file for hue-users-cm


- name: Copy script to create users in HUE
  copy: src="{{item}}" dest=/tmp mode=755
  with_items:
    - create-user-in-hue-cm.sh



- name: Create user in HUE
  command: /tmp/create-user-in-hue-cm.sh {{ item[0] }} {{ item[1] }} {{ item[2] }}
  with_nested:
    - "{{ users }}"
    - "{{ password_suffix }}"
    - "{{ hue_db_password }}"