---

- name: Copy script to test Hive
  copy: src="{{item}}" dest=/tmp mode=755
  with_items:
    - 2_hive.sh
    - common.sh
    - lion.tsv


- name: Test Hive operations
#  become: yes
#  become_user: hdfs
  register: out
  command: sudo -u hdfs /tmp/2_hive.sh

- debug: var=out.stdout_lines
