---
- name: Add repository for sbt
  get_url:
    url: https://bintray.com/sbt/rpm/rpm
    dest: /etc/yum.repos.d/bintray-sbt-rpm.repo
    mode: 0644


- name: Install required packages
  yum:
    state: latest
    name:
      - mysql
      - wget
      - nano
      - httpie
      - openssl
      - git
      - vim
      - python-setuptools
      - python-setuptools-devel
      - python-pip
      - unzip
      - sbt

- name: Install required Python libraries
  pip:
    name:
    - kafka-python
    - snakebite

- name: Add sqoop user
  user:
    name: sqoop
    group: sqoop
    comment: Sqoop

- name: Create client-directory for sqoop
  file:
    path: /var/lib/sqoop
    owner: sqoop
    group: sqoop
    mode: 0755
    state: directory

- name: Get MySQL connector
  unarchive:
    src: http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.38.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy MySQL connector to /var/lib/sqoop/
  command: cp /tmp/mysql-connector-java-5.1.38/mysql-connector-java-5.1.38-bin.jar /var/lib/sqoop
  become: yes
  become_user: root

# TODO: check if BigDataTutorial examples are still used

# - name: Copy scripts
#   copy:
#     src: "{{item}}"
#     dest: /tmp
#     mode: 755
#   with_items:
#     - build-examples.sh

# - name: Clone BigDataTutorial repo
#   git:
#     repo: https://github.com/getindata/BigDataTutorial.git
#     dest: /tmp/BigDataTutorial
#     force: yes

# - name: Make BigDataTutorial directory tree readable
#   file:
#     path: /tmp/BigDataTutorial
#     owner: root
#     recurse: yes

# - name: Build BigDataTutorial examples
#   command: /tmp/build-examples.sh

