---
# TODO: run on all hosts
- name: ntpd restart
  service: name=ntpd state=restarted

# TODO: run on all hosts
- name: set chkconfig ntpd on
  command: chkconfig ntpd on
  become: yes
  become_user: root

- name: Copy scripts
  copy: src="{{item}}" dest=/home/ec2-user mode=755
  with_items:
    - install-mvn.sh
    - install-shellinthebox.sh
    - build-examples.sh

- name: install-maven
  command: /home/ec2-user/install-mvn.sh
  become: yes
  become_user: root

- name: install-shellinthebox
  command: /home/ec2-user/install-shellinthebox.sh
  become: yes
  become_user: root

- name: install the latest version of openssl
  yum: name=openssl state=latest

- name: download stb
  get_url: url=https://bintray.com/sbt/rpm/rpm dest=/etc/yum.repos.d/bintray-sbt-rpm.repo mode=0644

- name: install the latest version of sbt
  yum: name=sbt state=latest

- name: install the latest version of git
  yum: name=git state=latest

- name: install the latest version of vim
  yum: name=vim state=latest

- name: install the latest version of python-setuptools
  yum: name=python-setuptools state=latest

- name: install the latest version of python-setuptools-devel
  yum: name=python-setuptools-devel state=latest

- name: install the latest version of snakebite
  easy_install: name=snakebite state=latest

- name: install the latest version of unzip
  yum: name=unzip state=latest

- name: clone big data repo
  git: repo=https://github.com/getindata/BigDataTutorial.git dest=/home/ec2-user/BigDataTutorial force=yes

- name: Make BigDataTutorial directory tree readable
  file: path=/home/ec2-user/BigDataTutorial owner=ec2-user recurse=yes

- name: build examples
  command: /home/ec2-user/build-examples.sh

- name: install python-pip
  yum: name=python-pip state=latest

# TODO: make it work
#- name: installing numpy
#  pip: name=numpy
