---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: adding group elasticsearch
  group: name=elasticsearch state=present

- name: adding user elasticsearch
  user: name=elasticsearch comment="Elastic Search" group=elasticsearch

- name: downloading elasticsearch 5.1.2
  command: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.zip -O /tmp/elasticsearch-5.1.2.zip

- name: unpacking elasticsearch to /opt/elasticsearch-5.1.2
  command: unzip -u /tmp/elasticsearch-5.1.2.zip -d /opt

- name: changing ownership of elasticsearch homedir to elasticsearch user
  file: path=/opt/elasticsearch-5.1.2 state=directory owner=elasticsearch group=elasticsearch mode=0755 recurse=yes

- name: copying supervisor includes for Elastic Search
  copy: src="{{item}}" dest=/etc/supervisor/conf.d/ mode=755
  with_items:
    - elasticsearch.conf

- name: starting/restarting supervisord
  service: name=supervisord state=restarted
  
