---
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: adding group elasticsearch
  group: name=elasticsearch state=present

- name: adding user elasticsearch
  user: name=elasticsearch comment="Elastic Search" group=elasticsearch

- name: downloading elasticsearch 2.3.1
  command: wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/elasticsearch/2.3.1/elasticsearch-2.3.1.zip -O /tmp/elasticsearch-2.3.1.zip

- name: unpacking elasticsearch to /opt/elasticsearch-2.3.1
  command: unzip -u /tmp/elasticsearch-2.3.1.zip -d /opt

- name: changing ownership of elasticsearch homedir to elasticsearch user
  file: path=/opt/elasticsearch-2.3.1 state=directory owner=elasticsearch group=elasticsearch mode=0755 recurse=yes

- name: copying supervisor includes for Elastic Search
  copy: src="{{item}}" dest=/etc/supervisor/conf.d/ mode=755
  with_items:
    - elasticsearch.conf

- name: starting/restarting supervisord
  service: name=supervisord state=restarted
  async: 45
  poll: 0
