---

- name: Copy script to install hue
  copy: src="{{item}}" dest=/home/ec2-user mode=755
  with_items:
    - configure-hue-db.sh
    - install-hue.sh
    - onboard-hue-user.sh
    - configure-hue-ini.sh
    - sync-hue-db.sh
    - restart-hue.sh

- name: Configure HUE db
  command: /home/ec2-user/configure-hue-db.sh
  become: yes
  become_user: root

- name: Install HUE
  command: /home/ec2-user/install-hue.sh
  become: yes
  become_user: root

- name: Onboard HUE user
  command: /home/ec2-user/onboard-hue-user.sh
  become: yes
  become_user: root

- name: Configure hue.ini
  command: /home/ec2-user/configure-hue-ini.sh
  become: yes
  become_user: root

- name: Synchronize Hue with the external database
  command: /home/ec2-user/sync-hue-db.sh
  become: yes
  become_user: root

- name: Restart HUE
  command: /home/ec2-user/restart-hue.sh
  become: yes
  become_user: root
